#define JM_VER
//#define HS_VER

using Photon.Pun;
using System.Collections;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using System;

public class PlayerHUD : MonoBehaviourPun, IPunObservable
{
    public static event Action onGameEnd = delegate { };
    enum PlayerColor
    {
        Blue,
        Red,
    }

    enum InfoState
    {
        Player,
        Tower,
        Minion,
        Nexus,
    }

    // ###############################################
    //             NAME : ARTSUNG                      
    //             MAIL : artsung410@gmail.com         
    // ###############################################

    [Header("PlayerStatusUI")]
    public GameObject PlayerObject;
    private Stats playerStat;
    private Player playerScript;
    public Image PlayerPortrait;                        // Ï¥àÏÉÅÌôî
    public Image playerHealthBar;                       // Ï≤¥Î†• Í≤åÏù¥ÏßÄ
    public Image playerExperienceBar;                   // Í≤ΩÌóòÏπò Í≤åÏù¥ÏßÄ
    public TextMeshProUGUI playerHealthBarTMpro;        // Ï≤¥Î†• text
    public TextMeshProUGUI playerExperienceBarTMpro;    // Í≤ΩÌóòÏπò text
    public TextMeshProUGUI PlayerLevelText;             // Î†àÎ≤® text
    public Text PlayerDpsText;                          // Ï¥àÎãπÍ≥µÍ≤©Î†• text
    public Text PlayerSpeedText;                        // Ïù¥ÎèôÏÜçÎèÑ text

    [Header("InfoUI")]
    public GameObject InfoPanel;
    public Image InfoIcon;
    public Image InfoHealthBar;
    public TextMeshProUGUI InfoHealthBarTMPro;
    public TextMeshProUGUI InfoDpsTMpro;
    public TextMeshProUGUI InfoSpdMpro;
    public TextMeshProUGUI InfoLevel;

    [Header("SkillUI")]
    public GameObject skillTable;

    [Header("ScoreUI")]
    public TextMeshProUGUI scoreTMPro;
    public TextMeshProUGUI timerTMPro;
    public static PlayerHUD Instance;

    [Header("GameResultUI")]
    public GameObject GameWinPanel;
    public Sprite GameWinSprite;
    public Sprite GameDefeatSprite;
    public GameObject GameResultImage;
    public Sprite GameResultWin;
    public Sprite GameResultDef;
    public Sprite GameResultDraw;

    private Health playerHp;
    private Health enemyHp;

    [Header("ChatUI")]
    public TMP_InputField ChatInput;
    public GameObject ChatPanel;
    public TextMeshProUGUI[] ChatText;
    private bool ChatingUi = false;
    private bool Chating = false;


    [Header("MousePointer")]
    public Canvas MousePointerCanvas;
    public GameObject MousePositionImage1;
    public GameObject MousePositionImage2;
    public MousePointer mousePointer;

    [Header("BossMonsterUI")]
    public GameObject BossSpawnNotification;



    private int[] playerScores = { 0, 0 };

    [HideInInspector]
    public float sec = 0;
    [HideInInspector]
    public int min = 0;

    [SerializeField]
    public bool BossMonsterSpawnON { get; private set; }

    Player currentPlayerforInfo;
    Turret currentTurretforInfo;
    Enemybase currentMinionforInfo;
    NexusHp currentNexusforInfo;

    WaitForSeconds Delay500 = new WaitForSeconds(5);

    public string lastDamageTeam;
    public bool NeutalMonsterDie = false;



    IEnumerator imigeCourutine;
    IEnumerator textCouruntine;
    IEnumerator resultImigePopup;

    InfoState INFO;

    // Ïù¥Îèô ÏùºÎ∞ò Ïª§ÏÑú
    [SerializeField]
    public Texture2D cursorMoveNamal;
    // Ïù¥Îèô ÏïÑÍµ∞ Ïª§ÏÑú
    [SerializeField]
    public Texture2D cursorMoveAlly;
    // Ïù¥Îèô Ï†ÅÍµ∞ Ïª§ÏÑú
    [SerializeField]
    public Texture2D cursorMoveEnemy;

    // Í≥µÍ≤© ÏùºÎ∞ò Ïª§ÏÑú
    [SerializeField]
    public Texture2D cusorAttackNomal;
    // Í≥µÍ≤© ÏïÑÍµ∞ Ïª§ÏÑú
    [SerializeField]
    public Texture2D cusorAttackAlly;
    // Í≥µÍ≤© Ï†ÅÍµ∞ Ïª§ÏÑú
    [SerializeField]
    public Texture2D cusorAttackEnemy;

    private void Awake()
    {
        Instance = this;
        Turret.turretMouseDownEvent += ActivationTowerInfoUI;
        Player.PlayerMouseDownEvent += ActivationEnemyInfoUI;
        Enemybase.minionMouseDownEvent += ActivationMinionInfoUI;
        NexusHp.nexusMouseDownEvent += ActivationNexusInfoUI;
    }

    private void OnEnable()
    {
        // Í≤åÏûÑ Ï†úÌïú ÏãúÍ∞Ñ Í¥ÄÎ†® ÏΩîÎìú
        TrojanHorse tro = GameObject.FindGameObjectWithTag("GetCaller").gameObject.GetComponent<TrojanHorse>();
        int time = 600;

        //Ïãú, Î∂Ñ, Ï¥à ÏÑ†Ïñ∏
        int hours, minute, second;

        //ÏãúÍ∞ÑÍ≥µÏãù
        hours = time / 3600;
        minute = time % 3600 / 60;
        second = time % 3600 % 60;
        min = minute;
        sec = second;
        BossSpawnNotification.SetActive(false);


        bossText = BossSpawnNotification.transform.GetChild(0).GetChild(0).GetComponent<TextMeshProUGUI>();
    }

    private void Start()
    {
        imigeCourutine = ImageFadeIn();
        //resultImigePopup = ResultImagePopUp();
        textCouruntine = textFadeout();

        StartCoroutine(SetPlayer());
        setSkill();
        StartCoroutine(setHp());
        setMouseCursor();
        //photonView.RPC("RPCInitScore", RpcTarget.All);
        for (int i = 0; i < ChatText.Length; i++)
        {
            ChatText[i].text = "";
        }
    }

    float testTime;

    private void FixedUpdate()
    {
        if (PhotonNetwork.IsMasterClient)
        {
            if (GameWinPanel.GetComponent<Image>().sprite == GameResultDraw)
            {
                testTime += Time.deltaTime;
                if (testTime >= 1f)
                {
                    if ((int)sec >= 60)
                    {
                        sec = 0;
                        min++;
                    }
                    sec += Time.deltaTime;
                }
            }
            else
            {
                if ((int)sec < 0) // 1 
                {
                    sec = 60;
                    min--;
                }
                sec -= Time.deltaTime;

                if (min <= 0 && sec <= 0)
                {
                    min = 0;
                    sec = 0;
                    isTimeEnd = true;
                }
            }

        }

        // ÏãúÍ∞ÑÏùÑ Ïù¥Ïö©Ìïú Íµ¨ÌòÑÎ∂ÄÎ∂Ñ
        Timer(min, sec, isTimeEnd);
    }

    void Update()
    {
        if (GameManager.Instance.isGameEnd == true)
        {
            return;
        }

        UpdateStatusUI();
        UpdateHealthUI();
        UpdateInfo();
        UpdateScore();

        if (false == Chating && Input.GetKeyDown(KeyCode.Return))
        {
            ChatingUi = !ChatingUi; //Ïò®Ïò§ÌîÑ
            ChatPanel.SetActive(Chating); // Ï±ÑÌåÖÏ∞ΩÏò®
            if (ChatingUi && ChatInput.text == "")
            {
                ChatingUi = false;
            }

        }
    }


    #region ‚ãÜ‚Å∫‚Çä‚ãÜ Skill Panel ‚ãÜ‚Å∫‚Çä‚ãÜ

    private void setSkill()
    {
        int count = GameObject.FindGameObjectWithTag("GetCaller").gameObject.GetComponent<TrojanHorse>().skillItems.Count;

        for (int i = 0; i < count; i++)
        {
            Item item = GameObject.FindGameObjectWithTag("GetCaller").gameObject.GetComponent<TrojanHorse>().skillItems[i];
            int slotIndex = GameObject.FindGameObjectWithTag("GetCaller").gameObject.GetComponent<TrojanHorse>().skillIndex[i];
            skillTable.transform.GetChild(slotIndex).GetChild(0).gameObject.SetActive(true);
            skillTable.transform.GetChild(slotIndex).GetChild(0).GetComponent<Skillicon>().item = item;
            skillTable.transform.GetChild(slotIndex).GetComponent<SkillButton>().item = item;
            skillTable.transform.GetChild(slotIndex).GetChild(0).GetComponent<Image>().sprite = SkillManager.Instance.Datas[i].SkillIcon;
        }
    }

    #endregion


    #region üï¶ Timer & Scroe Panel üï¶

    public bool isTimeEnd;
    float winnerTime;
    float neutralTime;
    void Timer(int min, float sec, bool end)
    {
        timerTMPro.text = string.Format("{0:D2}:{1:D2}", min, (int)sec);
        if (NeutalMonsterDie)
        {
            neutralTime += Time.deltaTime;
            Debug.Log("ÏãúÏûë");
            Debug.Log($"{GameManager.Instance.winner}");
            onGameEnd.Invoke();
            ResultPopUp(neutralTime, GameManager.Instance.winner);
            return;
        }

        // Ìò∏Ïä§Ìä∏Îäî Ï°∞Í±¥Î¨∏Ïù¥ Ïã§Ìñâ, ÌÅ¥ÎùºÏù¥Ïñ∏Ìä∏Îäî Ïã§ÌñâÏïàÎê®
        if (end == true) // 3
        {
            string gameWinMessage = "";
            Debug.Log("time's up");
            winnerTime += Time.deltaTime;
            if (playerScores[(int)PlayerColor.Blue] == playerScores[(int)PlayerColor.Red])
            {
                Debug.Log("&&&&&&&&&&&&&& Draw &&&&&&&&&&&&&&&");
                GameManager.Instance.winner = "Draw";
                Debug.Log(GameManager.Instance.winner);
                gameWinMessage = GameManager.Instance.winner;
                ResultPopUp(winnerTime, gameWinMessage);
                return;
            }
            else if (playerScores[(int)PlayerColor.Blue] > playerScores[(int)PlayerColor.Red])
            {
                Debug.Log("&&&&&&&&&&&&&& Blue &&&&&&&&&&&&&&&");
                GameManager.Instance.winner = "Blue";
                gameWinMessage = GameManager.Instance.winner;
                Debug.Log("Image Call");
                //StartCoroutine(resultImigePopup);
                ResultPopUp(winnerTime, gameWinMessage);
                GameManager.Instance.isGameEnd = true;
            }
            else if ((playerScores[(int)PlayerColor.Blue] < playerScores[(int)PlayerColor.Red]))
            {
                Debug.Log("&&&&&&&&&&&&&& Red &&&&&&&&&&&&&&&");
                GameManager.Instance.winner = "Red";
                gameWinMessage = GameManager.Instance.winner;
                Debug.Log("Image Call");
                ResultPopUp(winnerTime, gameWinMessage);
                GameManager.Instance.isGameEnd = true;
            }

            //photonView.RPC(nameof(RPCInitScore), RpcTarget.All); Ïôú ÌïÑÏöîÌïúÍ∞Ä?
            onGameEnd.Invoke();

        }
    }

    // Ìò∏Ïä§Ìä∏Í∞Ä Í¥ÄÎ¶¨ÌïòÎäî Î∂ÄÎ∂Ñ : ÏãúÍ∞Ñ, Í≤åÏûÑÏ¢ÖÎ£åÏó¨Î∂Ä, Ï†êÏàò
    public void OnPhotonSerializeView(PhotonStream stream, PhotonMessageInfo info)
    {
        if (stream.IsWriting && PhotonNetwork.IsMasterClient)
        {
            // We own this player: send the others our data
            stream.SendNext(sec);
            stream.SendNext(min);
            stream.SendNext(isTimeEnd);
            stream.SendNext(playerScores);
        }
        else if (stream.IsReading)
        {
            // Network player, receive data
            this.sec = (float)stream.ReceiveNext();
            this.min = (int)stream.ReceiveNext();
            this.isTimeEnd = (bool)stream.ReceiveNext();
            this.playerScores = (int[])stream.ReceiveNext();
        }
    }

    public void AddScoreToEnemy(string tag)
    {
        if (GameManager.Instance.winner == "Draw")
        {
            return;
        }

        if (tag == "Red")
        {
            playerScores[(int)PlayerColor.Blue] += 1;
        }
        else
        {
            playerScores[(int)PlayerColor.Red] += 1;
        }

        //photonView.RPC(nameof(RPCUpdateScoreText), RpcTarget.All, playerScores[0].ToString(), playerScores[1].ToString());
    }
    
    public void UpdateScore()
    {
        scoreTMPro.text = $"{playerScores[(int)PlayerColor.Blue]}        {playerScores[(int)PlayerColor.Red]}";
    }

    //[PunRPC]
    //private void RPCUpdateScoreText(string player1ScoreText, string player2ScoreText)
    //{
    //    scoreTMPro.text = $"{player1ScoreText}        {player2ScoreText}";
    //}

    //[PunRPC]
    //private void RPCInitScore()
    //{
    //    scoreTMPro.text = $"0        0";
    //}

    #endregion


    #region ‚öôÔ∏è MainMenu Panel ‚öôÔ∏è

    #endregion


    #region üö© GameResult Panel üö©

    private void ResultPopUp(float elapse, string winner)
    {
        if (winner == "Draw")
        {
            Debug.Log("Draw");
            if (PhotonNetwork.IsMasterClient)
            {
                GameWinPanel.GetComponent<Image>().sprite = GameResultDraw;
                GameWinPanel.SetActive(true);
                FadeinImige();
                if (elapse >= 5f)
                {
                    GameWinPanel.SetActive(false);
                    BossSpawnNotification.SetActive(true);
                    TextFadeOut();
                    //GameResultImage.transform.GetChild(0).GetChild(1).GetComponent<Image>().sprite = GameResultDraw;
                }
            }
            else
            {
                GameWinPanel.GetComponent<Image>().sprite = GameResultDraw;
                GameWinPanel.SetActive(true);
                FadeinImige();
                if (elapse >= 5f)
                {
                    GameWinPanel.SetActive(false);
                    BossSpawnNotification.SetActive(true);
                    TextFadeOut();
                    //GameResultImage.transform.GetChild(0).GetChild(1).GetComponent<Image>().sprite = GameResultDraw;
                }
            }
        }
        else if (winner == "Blue")
        {
            Debug.Log("Blue");
            if (PhotonNetwork.IsMasterClient)
            {
                GameWinPanel.GetComponent<Image>().sprite = GameWinSprite;
                GameWinPanel.SetActive(true);
                FadeinImige();
                if (elapse >= 5f)
                {
                    GameWinPanel.SetActive(false);
                    GameResultImage.SetActive(true);
                    GameResultImage.transform.GetChild(0).GetChild(1).GetComponent<Image>().sprite = GameWinSprite;
                }
            }
            else
            {
                GameWinPanel.GetComponent<Image>().sprite = GameDefeatSprite;
                GameWinPanel.SetActive(true);
                FadeinImige();
                if (elapse >= 5f)
                {
                    GameWinPanel.SetActive(false);
                    GameResultImage.SetActive(true);
                    GameResultImage.transform.GetChild(0).GetChild(1).GetComponent<Image>().sprite = GameDefeatSprite;
                }
            }
        }
        else if (winner == "Red")
        {
            Debug.Log("Red");
            if (PhotonNetwork.IsMasterClient)
            {
                GameWinPanel.GetComponent<Image>().sprite = GameDefeatSprite;
                GameWinPanel.SetActive(true);
                FadeinImige();
                if (elapse >= 5f)
                {
                    GameWinPanel.SetActive(false);
                    GameResultImage.SetActive(true);
                    GameResultImage.transform.GetChild(0).GetChild(1).GetComponent<Image>().sprite = GameDefeatSprite;
                }
            }
            else
            {
                GameWinPanel.GetComponent<Image>().sprite = GameWinSprite;
                GameWinPanel.SetActive(true);
                FadeinImige();
                if (elapse >= 5f)
                {
                    GameWinPanel.SetActive(false);
                    GameResultImage.SetActive(true);
                    GameResultImage.transform.GetChild(0).GetChild(1).GetComponent<Image>().sprite = GameWinSprite;
                }
            }
        }
    }

    // ÏäπÌå® Í≤∞Í≥º Ïù¥ÎØ∏ÏßÄ ÌåùÏóÖ Ìï®Ïàò
    //private IEnumerator ResultImagePopUp()
    //{
    //    Debug.Log($"result image popup start");
    //    Debug.Log(GameManager.Instance.winner);
    //    if (GameManager.Instance.winner == "Blue")
    //    {
    //        Debug.Log("2 "); 
    //        if (PhotonNetwork.IsMasterClient)
    //        {
    //            GameWinPanel.GetComponent<Image>().sprite = GameWinSprite;
    //            FadeinImige();
    //            Debug.Log("3");
    //            yield return Delay500;
    //            GameWinPanel.SetActive(false);
    //            GameResultImage.SetActive(true);
    //            GameResultImage.transform.GetChild(0).GetChild(1).GetComponent<Image>().sprite = GameResultWin;
    //        }
    //        else
    //        {
    //            GameWinPanel.GetComponent<Image>().sprite = GameDefeatSprite;
    //            FadeinImige();
    //            Debug.Log("4");
    //            yield return Delay500;
    //            GameWinPanel.SetActive(false);
    //            GameResultImage.SetActive(true);
    //            GameResultImage.transform.GetChild(0).GetChild(1).GetComponent<Image>().sprite = GameResultDef;
    //        }
    //    }
    //    else if (GameManager.Instance.winner == "Red")
    //    {
    //        if (PhotonNetwork.IsMasterClient)
    //        {
    //            GameWinPanel.GetComponent<Image>().sprite = GameDefeatSprite;
    //            FadeinImige();

    //            yield return Delay500;
    //            GameWinPanel.SetActive(false);
    //            GameResultImage.SetActive(true);
    //            GameResultImage.transform.GetChild(0).GetChild(1).GetComponent<Image>().sprite = GameResultDef;
    //        }
    //        else
    //        {
    //            GameWinPanel.GetComponent<Image>().sprite = GameWinSprite;
    //            FadeinImige();

    //            yield return Delay500;
    //            GameWinPanel.SetActive(false);
    //            GameResultImage.SetActive(true);
    //            GameResultImage.transform.GetChild(0).GetChild(1).GetComponent<Image>().sprite = GameResultWin;
    //        }
    //    }
    //    yield return null;
    //}

    // ÌéòÏù¥Îìú Ïù∏ Ìï®Ïàò
    private IEnumerator ImageFadeIn()
    {
        float fadeValue = 0;
        Image gameWinPanel = GameWinPanel.GetComponent<Image>();
        while (fadeValue <= 1.0f)
        {
            fadeValue += 0.01f;
            yield return new WaitForSeconds(0.01f);

            gameWinPanel.color = new Color(255, 255, 255, fadeValue);

            yield return null; // ÏΩîÎ£®Ìã¥ ÌïúÎ≤à ÎèÑÎäîÏßÄ ÌôïÏù∏Ìï¥Ï£ºÎäî ÏûëÏóÖ?
        }
    }

    public void ActivationGameWinUI_Nexus(string tag)
    {
        if (GameManager.Instance.isGameEnd == true)
        {
            return;
        }

        string gameWinMessage = "";
        if (tag == "Red")
        {
            GameManager.Instance.winner = "Blue";
            gameWinMessage = GameManager.Instance.winner;
        }
        else
        {
            GameManager.Instance.winner = "Red";
            gameWinMessage = GameManager.Instance.winner;
        }
        StartCoroutine(CorPopUp(gameWinMessage));
        GameManager.Instance.isGameEnd = true;
        onGameEnd.Invoke();

        //StartCoroutine(DelayLeaveRoom());
    }

    float nexusTime;
    IEnumerator CorPopUp(string str)
    {
        while (true)
        {
            nexusTime += Time.deltaTime;
            yield return null;
            ResultPopUp(nexusTime, str);
        }
    }

    private IEnumerator DelayLeaveRoom()
    {
        yield return new WaitForSeconds(7f);
        PhotonNetwork.LeaveRoom();
    }

    #endregion


    #region üì¢ Chatting Panel üì¢
    public void Sned()
    {
        string msg = PhotonNetwork.LocalPlayer.ActorNumber + " : " + ChatInput.text;
        photonView.RPC("ChatRPC", RpcTarget.All, PhotonNetwork.LocalPlayer.ActorNumber + " : " + ChatInput.text);
        ChatInput.text = "";
    }

    [PunRPC]
    void ChatRPC(string msg)
    {
        bool isInput = false;
        for (int i = 0; i < ChatText.Length; i++)

            if (ChatText[i].text == "")
            {
                isInput = true;
                ChatText[i].text = msg;
                break;

            }


        if (!isInput)
        {
            for (int i = 1; i < ChatText.Length; i++) ChatText[i - 1].text = ChatText[i].text;
            ChatText[ChatText.Length - 1].text = msg;
        }
    }
    #endregion


    #region üòÅ Player Status Panel üòÅ

    private IEnumerator setHp()
    {
        while (true)
        {
            yield return null;
            try
            {
                playerHp = GameManager.Instance.CurrentPlayers[0].GetComponent<Health>();
                Debug.Log(playerHp);
                enemyHp = GameManager.Instance.CurrentPlayers[1].GetComponent<Health>();
                Debug.Log(enemyHp);
                break;
            }
            catch (Exception ie)
            {
                print(ie);
            }
        }
        StopCoroutine(setHp());
    }

    float playerHp2D;
    void UpdateHealthUI()
    {
        if (playerHp == null)
        {
            return;
        }

        playerHealthBar.fillAmount = playerHp.health / playerHp.MaxHealth;
        playerHp2D = playerHp.health;
        playerHealthBarTMpro.text = (int)playerHp2D + " / " + playerHp.MaxHealth;
    }

    IEnumerator SetPlayer()
    {
        while (true)
        {
            try
            {
                PlayerObject = GameManager.Instance.CurrentPlayers[0];
                playerStat = PlayerObject.GetComponent<Stats>();
                playerScript = PlayerObject.GetComponent<Player>();
                yield break;
            }
            catch (Exception)
            {
                Debug.Log("ÌîåÎ†àÏù¥Ïñ¥ Í∞ÄÏ†∏Ïò§ÎäîÏ§ë");
            }
            yield return new WaitForSeconds(0.1f);
        }
    }

    private void UpdateStatusUI()
    {
        // Í≤ΩÌóòÏπò
        playerExperienceBarTMpro.text = $"{playerStat.acquiredExp} / {playerStat.maxExp}";

        // Í≤ΩÌóòÏπò Î∞î
        playerExperienceBar.fillAmount = playerStat.acquiredExp / playerStat.maxExp;

        // DPS
        PlayerDpsText.text = $"{Math.Round(playerStat.attackDmg / playerStat.attackSpeed)}";

        // Ïù¥ÎèôÏÜçÎèÑ
        PlayerSpeedText.text = $"{Math.Round(playerStat.moveSpeed)}";

        // Ï¥àÏÉÅÌôî
        PlayerPortrait.sprite = playerScript.playerIcon;

        // Î†àÎ≤®
        PlayerLevelText.text = $"{playerStat.Level}";
    }

    #endregion


    #region üïÆ Info Panel üïÆ

    float Hp2D;
    public void UpdateInfo()
    {
        if (INFO == InfoState.Player)
        {
            if (enemyHp == null)
            {
                return;
            }

            if (currentPlayerforInfo == null)
            {
                return;
            }

            if (enemyHp.health <= 0)
            {
                InfoPanel.SetActive(false);
            }

            InfoHealthBar.fillAmount = enemyHp.health / enemyHp.MaxHealth;
            Hp2D = enemyHp.health;
            InfoHealthBarTMPro.text = (int)Hp2D + " / " + enemyHp.MaxHealth;

            float dmg = currentPlayerforInfo.playerStats.attackDmg;
            float atkSpeed = currentPlayerforInfo.playerStats.attackSpeed;
            float moveSpeed = currentPlayerforInfo.playerStats.moveSpeed;
            float dps = dmg * atkSpeed;

            InfoDpsTMpro.text = dps.ToString();
            InfoSpdMpro.text = moveSpeed.ToString();
        }

        else if (INFO == InfoState.Tower)
        {
            if (currentTurretforInfo == null)
            {
                return;
            }

            if (currentTurretforInfo.currentHealth <= 0)
            {
                InfoPanel.SetActive(false);
            }

            // Ïã§ÏãúÍ∞Ñ Ï≤¥Î†• ÎèôÍ∏∞Ìôî
            InfoHealthBar.fillAmount = currentTurretforInfo.currentHealth / currentTurretforInfo.maxHealth;
            Hp2D = currentTurretforInfo.currentHealth;
            InfoHealthBarTMPro.text = (int)Hp2D + " / " + currentTurretforInfo.maxHealth;
        }

        else if (INFO == InfoState.Minion)
        {
            if (currentMinionforInfo == null)
            {
                return;
            }

            if (currentMinionforInfo.CurrnetHP <= 0)
            {
                InfoPanel.SetActive(false);
            }

            InfoHealthBar.fillAmount = currentMinionforInfo.CurrnetHP / currentMinionforInfo.HP;
            Hp2D = currentMinionforInfo.CurrnetHP;
            InfoHealthBarTMPro.text = (int)Hp2D + " / " + currentMinionforInfo.HP;
        }

        else if (INFO == InfoState.Nexus)
        {
            if (currentNexusforInfo == null)
            {
                return;
            }

            if (currentNexusforInfo.CurrentHp <= 0)
            {
                InfoPanel.SetActive(false);
            }

            InfoHealthBar.fillAmount = currentNexusforInfo.CurrentHp / currentNexusforInfo.MaxHp;
            Hp2D = currentNexusforInfo.CurrentHp;
            InfoHealthBarTMPro.text = (int)Hp2D + " / " + currentNexusforInfo.MaxHp;
        }
    }

    public void ActivationEnemyInfoUI(Player player)
    {
        INFO = InfoState.Player;
        currentPlayerforInfo = player;
        InfoPanel.SetActive(true);

        InfoIcon.sprite = player.playerIcon;
        InfoLevel.text = player.playerStats.Level.ToString();
    }

    public void ActivationTowerInfoUI(Turret turret)
    {
        INFO = InfoState.Tower;
        currentTurretforInfo = turret;
        InfoPanel.SetActive(true);

        float dmg = currentTurretforInfo.attack;
        float atkSpeed = currentTurretforInfo.attackSpeed;
        float dps = dmg * atkSpeed;

        InfoDpsTMpro.text = dps.ToString();
        InfoSpdMpro.text = 0.ToString();
        InfoLevel.text = turret.towerDB.Rank.ToString();
        InfoIcon.sprite = turret.towerDB.Sprite_TowerProtrait;
    }

    public void ActivationMinionInfoUI(Enemybase minion, Sprite icon)
    {
        INFO = InfoState.Minion;
        currentMinionforInfo = minion;
        InfoPanel.SetActive(true);

        float dmg = minion.Damage;
        float atkSpeed = minion.AttackSpeed;
        float spd = minion.moveSpeed;
        float dps = dmg * atkSpeed;

        InfoDpsTMpro.text = dps.ToString();
        InfoSpdMpro.text = spd.ToString();
        InfoLevel.text = minion.minionDB.Rank.ToString();

        // Îì§Ïñ¥Ïò® ÏïÑÏù¥ÏΩòÏù¥ Ïö©ÏùºÎïå Î¶¨ÌÑ¥
        if(icon.name == "Dragonknight18")
        {
            InfoIcon.sprite = icon;
            return;
        }

        if (minion.gameObject.tag == "Blue")
        {
            InfoIcon.sprite = minion.minionDB.Icon_Blue;
        }
        else if (minion.gameObject.tag == "Red")
        {
            InfoIcon.sprite = minion.minionDB.Icon_Red;
        }
        else
        {
            InfoIcon.sprite = icon;
        }
    }

    public void ActivationNexusInfoUI(NexusHp nexus, Sprite icon)
    {
        INFO = InfoState.Nexus;
        currentNexusforInfo = nexus;
        InfoPanel.SetActive(true);

        InfoIcon.sprite = icon;
        InfoDpsTMpro.text = 0.ToString();
        InfoSpdMpro.text = 0.ToString();
    }

    #endregion


    #region üîë InGame System üîë

    private void setMouseCursor()
    {
        GameManager.Instance.CurrentPlayers[0].GetComponent<PlayerBehaviour>().moveMouseCanvas = MousePointerCanvas;
        GameManager.Instance.CurrentPlayers[0].GetComponent<PlayerBehaviour>().moveMouseObj1 = MousePositionImage1;
        GameManager.Instance.CurrentPlayers[0].GetComponent<PlayerBehaviour>().moveMouseObj2 = MousePositionImage2;
        GameManager.Instance.CurrentPlayers[0].GetComponent<PlayerBehaviour>().moveMousePointer = mousePointer;
    }

    #endregion

    private void FadeinImige()
    {
        StartCoroutine(imigeCourutine);
    }

    private IEnumerator textFadeout()
    {
        float fadeValue = 1f;

        TextMeshProUGUI bossText = BossSpawnNotification.transform.GetChild(0).GetChild(0).GetComponent<TextMeshProUGUI>();

        while (true)
        {
            fadeValue -= 0.2f;
            yield return new WaitForSeconds(1f);
            if (fadeValue <= 0f && BossMonsterSpawnON == false)
            {
                BossMonsterSpawnON = true;
                GameManager.Instance.bossMonsterSpawn();
                yield break;
            }

            bossText.color = new Color(255, 255, 255, fadeValue);
            yield return null;

        }
    }

    float fadeTest = 1f;
    TextMeshProUGUI bossText;
    public void TextFadeOut()
    {
        fadeTest -= 0.01f;
        if (BossMonsterSpawnON)
        {
            return;
        }

        if (fadeTest <= 0f && BossMonsterSpawnON == false)
        {
            BossMonsterSpawnON = true;
            GameManager.Instance.bossMonsterSpawn();
        }
        bossText.color = new Color(255, 255, 255, fadeTest);
    }


    #region Report System

    [Header("ReportUI")]
    public GameObject ReportPanel;
    [SerializeField]
    private GameObject SuccessPanel;
    [SerializeField]
    private TextOverFlow textoverflow;
    private bool CheckboxOn = false;
    private  bool button = false;

    public void RefortButton()
    {
        button = !button;
        if (false == button)
        {
            ReportPanel.transform.GetChild(2).GetChild(0).GetComponent<TextMeshProUGUI>().color = Color.white;
            ReportPanel.transform.GetChild(3).GetChild(0).GetComponent<TextMeshProUGUI>().color = Color.white;
            textoverflow.gameObject.transform.GetChild(0).GetChild(3).gameObject.SetActive(false);
            textoverflow.gameObject.transform.GetChild(0).GetChild(4).gameObject.SetActive(false);
            CheckboxOn = false;
            textoverflow.text.text = "";
        }
        ReportPanel.SetActive(button);
        textoverflow.gameObject.transform.GetChild(0).GetChild(3).gameObject.SetActive(false);
    }


    public void Checkbox(int value)
    {
        CheckboxOn = true;
        if (value == 0)
        {
            ReportPanel.transform.GetChild(2).GetChild(0).GetComponent<TextMeshProUGUI>().color = Color.yellow;
            ReportPanel.transform.GetChild(3).GetChild(0).GetComponent<TextMeshProUGUI>().color = Color.white;

        }
        else
        {
            ReportPanel.transform.GetChild(2).GetChild(0).GetComponent<TextMeshProUGUI>().color = Color.white;
            ReportPanel.transform.GetChild(3).GetChild(0).GetComponent<TextMeshProUGUI>().color = Color.yellow;
        }


    }

    public void SendReport() // 2 ÏûÖÎ†•ÏïàÌñáÏùÑÎïå  3 Ï≤¥ÌÅ¨Î∞ïÏä§ Ï≤¥ÌÅ¨ÏïàÌñáÏùÑÎïå  4 Í∏ÄÏûêÏàò Ïò§Î∞îÎê¨ÏùÑÎïå
    {
        Debug.Log($"{textoverflow.textNotEnter} : {CheckboxOn}");

        if (!textoverflow.textNotEnter && CheckboxOn) //Ï≤¥ÌÅ¨Î∞ïÏä§ ÎêòÏûàÍ≥† Í∏ÄÏûêÏàò ÏûàÏùÑÎïå
        {
            
            SuccessPanel.SetActive(true);
        }
        else if (textoverflow.textNotEnter == true) // Í∏ÄÏûêÏïÑÎ¨¥Í≤ÉÎèÑ ÏïàÏûÖÎ†•ÌñáÏùÑÎïå
        {
            

            textoverflow.gameObject.transform.GetChild(0).GetChild(3).gameObject.SetActive(true);
            textoverflow.gameObject.transform.GetChild(0).GetChild(4).gameObject.SetActive(false);

            // ÌÖçÏä§Ìä∏ Ïù¥ÎØ∏ÏßÄ Ï∂úÎ†•
            return;
        }
        else if (CheckboxOn == false)
        {

            
            textoverflow.gameObject.transform.GetChild(0).GetChild(3).gameObject.SetActive(false);
            textoverflow.gameObject.transform.GetChild(0).GetChild(4).gameObject.SetActive(true);
            return;
        }
    }

    #endregion

    private void OnDisable()
    {
        Instance = null;
    }
}